/*****************************
Author:       Duane Billue
Date:         2019-11-23
Description:  AV database objects script
*****************************/

SET SERVEROUTPUT ON
SET AUTOPRINT ON

-- Table Order

--=================--
--    12C
--=================--

CREATE TABLE "ORDERS"
(
  "ORDERS_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "ORDER_NUMBER" VARCHAR(250),
  "ORDER_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL,
	"ORDER_STATUS" NUMBER(2,0), 
	"ORDER_TOTAL" NUMBER(8,2)
);
/
--=================--
--    Pre 12C
--=================--

/*
CREATE TABLE "ORDERS"
(
  "ORDER_ID" VARCHAR2(10 BYTE) PRIMARY KEY,
  "ORDER_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL,
	"ORDER_STATUS" NUMBER(2,0), 
	"ORDER_TOTAL" NUMBER(8,2)
)

ALTER TABLE "ORDERS" ADD
CONSTRAINT av_order_pk PRIMARY KEY ("ORDER_ID");

CREATE SEQUENCE av_orders_sequence START WITH 1;

CREATE OR REPLACE TRIGGER av_orders_trigger
BEFORE INSERT ON "ORDER"
FOR EACH ROW

BEGIN
	SELECT av_orders_sequence.NEXTVAL 
	INTO :new.ID
	FROM dual;
END;
*/

/*
DROP TABLE ORDERS;
DROP SEQUENCE av_order_sequence;
DROP TRIGGER av_orders_trigger;
*/
--================================--

-- Table OrderItems

--=================--
--    12C
--=================--

CREATE TABLE "ORDERITEMS"
(
  ORDERITEMS_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ORDER_ID NUMBER(10) NOT NULL,
  ORDERITEMS_JSON_LIST VARCHAR2(4000)
);
/

--=================--
--    Pre 12C
--=================--

/*
CREATE TABLE "ORDERITEMS"
(
  ORDERITEMS_ID NUMBER(10) NOT NULL,
  ORDER_ID NUMBER(10) NOT NULL,
  ORDERITEMS_JSON_LIST VARCHAR2(4000)
)

ALTER TABLE "ORDERITEMS"
ADD CONSTRAINT av_json_check CHECK(ORDERITEMS_JSON_LIST IS JSON);

ALTER TABLE "ORDERITEMS" ADD
CONSTRAINT av_orderitems_pk PRIMARY KEY ("ORDERITEMS_ID");

CREATE SEQUENCE av_orderitems_sequence START WITH 1;

CREATE OR REPLACE TRIGGER av_orderitems_trigger
BEFORE INSERT ON "ORDERITEMS"
FOR EACH ROW

BEGIN
	SELECT av_orderitems_sequence.NEXTVAL 
	INTO :new.ID
	FROM dual;
END;
*/

/*
DROP TABLE ORDERITEMS;
DROP SEQUENCE av_orderitems_sequence;
DROP TRIGGER av_orderitems_trigger;
*/

--================================--
-- Table Product

--=================--
--    12C
--=================--

CREATE TABLE "PRODUCTS"
(
  PRODUCTS_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  PRODUCT_IMAGE BLOB,
  PRODUCT_VALUES CLOB
);
/

--=================--
--    Pre 12C
--=================--

/*
CREATE TABLE "PRODUCTS"
(
  PRODUCTS_ID NUMBER(10) NOT NULL,
  PRODUCT_IMAGE BLOB,
  PRODUCT_VALUES CLOB
)

CREATE SEQUENCE av_products_sequence START WITH 1;

CREATE OR REPLACE TRIGGER av_products_trigger
BEFORE INSERT ON "PRODUCT"
FOR EACH ROW

BEGIN
	SELECT av_products_sequence.NEXTVAL 
	INTO :new.ID
	FROM dual;
END;

/*
DROP TABLE PRODUCTS;
DROP SEQUENCE av_products_sequence;
DROP TRIGGER av_products_trigger;
*/
