FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY BlazorDock.sln /app
COPY BlazorDock.csproj /app
#RUN dotnet restore

COPY . /app
WORKDIR /app
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
RUN ls ./
ENTRYPOINT ["dotnet", "BlazorDock.dll"]